# Generated by Django 5.1.4 on 2025-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "code_uic",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100)),
                ("short_label", models.CharField(max_length=50)),
                ("long_label", models.CharField(max_length=150)),
            ],
        ),
    ]
